### ISSUE TITLE
Doesn't work with AnkiConnect 

### ISSUE THREAD

**Issue by avc1657** [voczi/anki-addons#1]
Hi, amazing yet simple addon. I always wanted something like an auto refresh for the browser. But the addon doesn't work when you add a card through AnkiConnect (another addon) with tools like Yomitan.

**Comment by voczi** [comment]
Can you try the new version of this addon with "Dirty hook" enabled in the addon settings? Make sure to restart afterwards.
Let me know if it's solved. Thanks!

**Comment by avc1657** [comment]
Solved! Nice!

**Comment by Geniusssmit** [comment]
Please make it work no matter what's in the browser's search box.

**Comment by voczi** [comment]
@Geniusssmit You can create a new issue and describe your problems.
