### ISSUE TITLE
browser's search box

### ISSUE THREAD

**Issue by Geniusssmit** [voczi/anki-addons#2]
Please make it work no matter what's in the browser's search box. If you add something in a deck that's not in the search box, the addon won't work.

**Comment by voczi** [comment]
Thank you for posting the issue.
There's sadly no way of making this addition without some rather ugly code, that would break further down the line. It's just the way that Anki is structured. I think it's best if I close this as not planned, and hopefully there will be a future where this feature can be done in a clean way with Anki.

**Comment by Geniusssmit** [comment]
got you, IG keeping added:1 in the search will do for now

**Comment by voczi** [comment]
Glad you understand.
